### ISSUE TITLE
I want to confirm if we create dom elements and add them to a div in html file after it has been processed,Now would the DOM tree created using your DOM-inspector would update automatically?

### ISSUE THREAD

**Issue by akshitjain** [janmyler/DOM-inspector#1]

**Comment by janmyler** [comment]
Hi @akshitjain, that's a good question. And the answer is no, it won't update the rendered DOM tree. 

The rendering of DOM tree happens just once, when the DOM inspector script is executed. There could be a use of [MutationObserver API](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) to listen for changes in DOM tree and re-rendering on them.

**Comment by akshitjain** [comment]
Thanks @janmyler
